### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Create `SECURITY.md` for GitPack.

### CODE REVIEW

**Review by CodeMaster7000 — CHANGES_REQUESTED** [review]
Ask people to open an issue for minor issues for the TDI team to resolve them.

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 Address these changes then I can merge.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 I have done this.

**Review by CodeMaster7000 — APPROVED** [review]
Thank you!

**Pull request merged**
